### ISSUE TITLE
Some questions about this project

### ISSUE THREAD

**Issue by wlhgit** [epic-kitchens/C8-Object-Tracking#1]
Thank you very much for sharing this amazing work! However, when we run "python download.py" and after the mp3 file has been downloaded, we encounter the error "No such file or directory: 'ffmpeg'". We would appreciate it if you could tell us what the problem is. Thank you so much for your consideration.

**Comment by wlhgit** [comment]
<img width="772" alt="0240518184322" src="https://github.com/epic-kitchens/C8-Object-Tracking/assets/112625021/8fa34376-783f-4308-a0e4-d64e349dfc43">

**Comment by wlhgit** [comment]
![385b27cd569a79a84b8d540cad57eda](https://github.com/epic-kitchens/C8-Object-Tracking/assets/112625021/95227dcc-ddda-479a-9c4e-297f6a6282e9)

**Comment by dimadamen** [comment]
To clarify, have you *already* downloaded the EPIC-KITCHENS dataset itself?

**Comment by wlhgit** [comment]
We have already run the previous commands from the GitHub repository. Isn't the dataset supposed to be downloaded in this step?

**Comment by matteo-dunnhofer** [comment]
Hi @wlhgit,

did you install the ffmpeg command on your machine?

**Comment by wlhgit** [comment]
We've run 'pip install ffmpeg' and then retried 'python download.py', but it gave an error message: 'FileNotFoundError: [Errno 2] No such file or directory: './TREK-150/P03_02/frame_0000001561.jpg'. However, we noticed that our P03_02 folder is actually empty.
![图片](https://github.com/epic-kitchens/C8-Object-Tracking/assets/112625021/c1afdb86-b89d-4415-a15c-ef006a7b1b42)

**Comment by matteo-dunnhofer** [comment]
You have to install the ffmpeg command line tool (see here https://ffmpeg.org/) not the Python package. The folder is empty because frames have not been extracted from the mp4 videos, due to the fact that no ffmpeg command was run.

**Comment by wlhgit** [comment]
Thank you so much for helping me address this difficulty！
